# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Live config reload (changes require restart)
live_config_reload = true

# Catppuccin "Macchiato" Theme
# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
  # Cursor blinking interval in milliseconds.
blink_interval = 750
  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
thickness = 0.15
  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
unfocused_hollow = true
  # If the vi mode cursor style is "None" or not specified, it will fall back to the active value of the normal cursor.
  # Values for `vi_mode_style`:
  #     - { <shape>, <blinking> } | "None"
vi_mode_style = "Beam"

[cursor.style]
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
blinking = "Off"
  # Cursor style
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 19.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
# family = "RobotoMono Nerd Font Mono"
style = "Regular"


[font.italic]
style = "Italic"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.glyph_offset]
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
x = 0
y = 0

[font.offset]
  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
x = 1
y = 1

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[scrolling]
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
history = 5000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
multiplier = 10

[selection]
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
  # Shell
  #
  # You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
  # Entries in `shell.args` are passed unmodified as arguments to the shell.
  #
  # Default:
  #   - (macOS) /bin/bash --login
  #   - (Linux/BSD) user login shell
  #   - (Windows) powershell
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "tmux"]

[window]
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
decorations = "Buttonless"

  # Window opacity 
  #
  # Values for `opacity`:
  #     - 0.0 to 1.0: The value 0.0 is completely transparent and 1.0 is opaque. Default value is 1.0
opacity = 0.8

  # Blurred window
  #
  # Values for `blur`: 
  #     - true | false # (works on macOS/KDE Wayland). Default value is false
blur = true

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed 
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
startup_mode = "Windowed"
  # Window title
title = "Alacritty"

[window.class]
  # Window class (Linux/BSD only):

  # General application class
general = "Alacritty"
  # Application instance name
instance = "Alacritty"

[window.dimensions]
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
columns = 125
lines = 32

[window.padding]
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
x = 7
y = 7

[window.position]
  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
x = 60
y = 115
